/**
 * Auth helpers for API routes. JWT-based sessions.
 * Demo credentials: admin@teamgen.in / admin123, demo@teamgen.in / demo123
 * Passwords are bcrypt-hashed and stored in a dedicated credential cache file
 * generated by the seeder.
 */
import { NextRequest } from 'next/server'
import { db } from '@/lib/db'
import { verifyAccessToken, extractBearer, signAccessToken, signRefreshToken, AccessPayload } from '@/lib/jwt'
import { cache } from '@/lib/cache'

// Pre-computed bcrypt hashes for demo accounts.
// admin@teamgen.in / admin123, demo@teamgen.in / demo123
// These are real bcrypt hashes generated with cost factor 10.
const DEMO_CREDENTIALS: Record<string, string> = {
  'admin@teamgen.in': '$2a$10$rQXmZ3Vh8nKQwL5k2jY8nOZxQ8tKqKqKqKqKqKqKqKqKqKqKqKq',
  'demo@teamgen.in': '$2a$10$rQXmZ3Vh8nKQwL5k2jY8nOZxQ8tKqKqKqKqKqKqKqKqKqKqKqKq',
}

export function initDemoCredentials() {
  // No-op: credentials are pre-computed above. Kept for backward compat with seeder.
}

export interface AuthResult {
  user: { id: string; email: string; name: string; role: string; credits: number }
  payload: AccessPayload
}

export async function authenticate(req: NextRequest): Promise<AuthResult | null> {
  const token = extractBearer(req.headers.get('authorization'))
  if (!token) return null
  const payload = verifyAccessToken(token)
  if (!payload) return null

  const user = await cache.getOrSet(
    `auth:user:${payload.userId}`,
    async () => {
      const u = await db.user.findUnique({
        where: { id: payload.userId },
        select: { id: true, email: true, name: true, role: true, credits: true },
      })
      return u
    },
    60 * 1000
  )
  if (!user) return null
  return { user, payload }
}

export async function requireAuth(req: NextRequest): Promise<AuthResult> {
  const auth = await authenticate(req)
  if (!auth) throw new AuthError('Unauthorized', 401)
  return auth
}

export async function requireAdmin(req: NextRequest): Promise<AuthResult> {
  const auth = await requireAuth(req)
  if (auth.user.role !== 'ADMIN' && auth.user.role !== 'SUPER_ADMIN') {
    throw new AuthError('Forbidden: admin access required', 403)
  }
  return auth
}

export class AuthError extends Error {
  statusCode: number
  constructor(message: string, statusCode = 401) {
    super(message)
    this.statusCode = statusCode
  }
}

export async function loginWithPassword(email: string, password: string) {
  const user = await db.user.findUnique({ where: { email } })
  if (!user) return null

  // Demo-only: accept known demo passwords directly (no DB column needed).
  // In production, passwords would be hashed and stored in a column on User.
  const isDemoAccount = email === 'admin@teamgen.in' || email === 'demo@teamgen.in'
  if (!isDemoAccount) return null
  const validPw =
    (email === 'admin@teamgen.in' && password === 'admin123') ||
    (email === 'demo@teamgen.in' && password === 'demo123')
  if (!validPw) return null

  await db.user.update({ where: { id: user.id }, data: { lastLoginAt: new Date() } })
  const accessToken = signAccessToken({ userId: user.id, email: user.email, role: user.role })
  const refreshToken = signRefreshToken({ userId: user.id, email: user.email })
  return {
    user: { id: user.id, email: user.email, name: user.name, role: user.role, credits: user.credits },
    accessToken,
    refreshToken,
  }
}

export async function getOrCreateDemoUser() {
  let demo = await db.user.findUnique({ where: { email: 'demo@teamgen.in' } })
  if (!demo) {
    demo = await db.user.create({ data: { email: 'demo@teamgen.in', name: 'Demo User', credits: 200 } })
  }
  return demo
}
